# Optionally, you can provide a default redirect URL for web visitors who
# navigate to a package that doesn't exist. If not provided, a barebones 404
# page will be returned.
default_redirect = "https://example.com"

# Every package you want importbounce to handle should be configured like the
# examples below.

[[packages]]
# The import path prefix. This must match a full segment of the requested
# import path for this config to apply. For example, this config would not
# match "example.com/gitpackagexyz".
prefix = "example.com/gitpackage"

# The combination of "vcs" and "repo-root" to use in the "go-import" meta tag,
# as described at https://golang.org/cmd/go/#hdr-Remote_import_paths.
import = "git https://git.example.com/example/gitpackage"

# The site to which web visitors should be redirected. This can be a pkg.go.dev
# link, a GitHub link, a link to your website, etc.
redirect = "https://pkg.go.dev/git.example.com/example/gitpackage"

# Multiple package configs are supported. The first config in the file whose
# prefix matches the requested import path is used.
[[packages]]
prefix = "example.com/mymodule"
import = "mod https://gomodules.example.com"
redirect = "https://example.com/projects/mymodule/"
